services:
  auth-infra-server:
    platform: linux/amd64
    image: auth-infra-server
    build:
      context: .
      dockerfile: ./docker/amd64/Dockerfile.authentik-server
  auth-infra-ldap:
    platform: linux/amd64
    image: auth-infra-ldap
    build:
      context: .
      dockerfile: ./docker/amd64/Dockerfile.authentik-ldap
