FROM ghcr.io/goauthentik/ldap:latest
LABEL org.opencontainers.image.source=https://github.com/tak-nz/auth-infra-ldap
LABEL org.opencontainers.image.description="Authentik LDAP outpost for TAK server auth via LDAP"
LABEL org.opencontainers.image.licenses=MIT
COPY authentik/blueprints/* /blueprints/ldap/
ENTRYPOINT ["/ldap"]
