FROM ghcr.io/goauthentik/server:latest
COPY authentik/blueprints/* /blueprints/ldap/
ENTRYPOINT [dumb-init -- ak]
LABEL org.opencontainers.image.source=https://github.com/tak-nz/auth-infra
LABEL org.opencontainers.image.description="Authentik server for TAK server auth via LDAP"
LABEL org.opencontainers.image.licenses=MIT