name: Production Deployment

on:
  push:
    tags: ['v*']
  workflow_dispatch:
    inputs:
      force_deploy:
        description: 'Force deployment without tag'
        required: false
        type: boolean
        default: false

permissions:
  id-token: write
  contents: read

jobs:
  test:
    uses: ./.github/workflows/cdk-test.yml

  build-images:
    uses: ./.github/workflows/production-build.yml
    secrets: inherit

  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    needs: [test, build-images]
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Setup CDK Environment
        uses: ./.github/actions/setup-cdk
        with:
          aws-role-arn: ${{ secrets.AWS_ROLE_ARN }}
          aws-region: ${{ secrets.AWS_REGION }}
          role-session-name: GitHubActions-Production

      - name: Bootstrap CDK (if needed)
        run: |
          if ! aws cloudformation describe-stacks --stack-name CDKToolkit 2>/dev/null; then
            npx cdk bootstrap aws://${{ secrets.AWS_ACCOUNT_ID }}/${{ secrets.AWS_REGION }} --context envType=prod
          fi

      - name: Extract Image Tags
        id: images
        run: |
          VERSION=$(jq -r '.context."prod".authentik.authentikVersion' cdk.json)
          BRANDING=$(jq -r '.context."prod".authentik.branding' cdk.json)
          REVISION=$(jq -r '.context."prod".authentik.buildRevision' cdk.json)
          
          AUTHENTIK_TAG="authentik-${VERSION}-${BRANDING}-r${REVISION}"
          LDAP_TAG="ldap-${VERSION}-r${REVISION}"
          
          echo "authentik-tag=$AUTHENTIK_TAG" >> $GITHUB_OUTPUT
          echo "ldap-tag=$LDAP_TAG" >> $GITHUB_OUTPUT

      - name: Validate Production Change Set
        run: |
          # Check if override is requested
          COMMIT_MSG="${{ github.event.head_commit.message }}"
          if [[ "$COMMIT_MSG" == *"[force-deploy]"* ]]; then
            echo "🚨 Force deploy detected - skipping change set validation"
          else
            ./scripts/github/validate-changeset.sh TAK-${{ vars.STACK_NAME }}-AuthInfra
          fi

      - name: Deploy Production
        run: npm run cdk deploy -- --context envType=prod --context stackName=${{ vars.STACK_NAME }} --context adminUserEmail=${{ vars.AUTHENTIK_ADMIN_EMAIL }} --context usePreBuiltImages=true --context authentikImageTag=${{ steps.images.outputs.authentik-tag }} --context ldapImageTag=${{ steps.images.outputs.ldap-tag }} --require-approval never